behavior:
  idle_timeout: 10s
  resume_after_inactivity: true
  pause_when_user_is_active: true
activities:
  - kind: mouse
    enabled: false
    interval: 5s
    pattern: square
  - kind: keyboard
    enabled: true
    interval: 5s
debug: true
logfile: ""